const errorCatalog = {
	400: {
		BAD_REQUEST_ERROR: 'BAD_REQUEST_ERROR',
		SAME_EMAIL_ERROR: 'SAME_EMAIL_ERROR',
		SAME_USERNAME_ERROR: 'SAME_USERNAME_ERROR',
		ROOM_ALREADY_EXISTS: 'ROOM_ALREADY_EXISTS',
		TERMS_NOT_ACCEPTED: 'TERMS_NOT_ACCEPTED',
		PRIVACY_POLICY_NOT_ACCEPTED: 'PRIVACY_POLICY_NOT_ACCEPTED',
		OLD_PASSWORD_NOT_MATCH_ERROR: 'OLD_PASSWORD_NOT_MATCH_ERROR',
		CART_QUANTITY_ZERO_ERROR: 'CART_QUANTITY_ZERO_ERROR',
		CART_ITEM_DOES_NOT_BELONG_SELECT_MARKET: 'CART_ITEM_DOES_NOT_BELONG_SELECT_MARKET',
	},
	401: {
		UNAUTHORIZED_ERROR: 'UNAUTHORIZED_ERROR',
		AUTH_EXPIRED_TOKEN_ERROR: 'AUTH_EXPIRED_TOKEN_ERROR',
		AUTH_INVALID_TOKEN_ERROR: 'AUTH_INVALID_TOKEN_ERROR',
		AUTH_NO_AUTHORIZATION_IN_COOKIE_ERROR: 'AUTH_NO_AUTHORIZATION_IN_COOKIE_ERROR',
		CREDENTIALS_TYPE_ERROR: 'CREDENTIALS_TYPE_ERROR',
		AUTH_INVALID_CREDENTIALS_ERROR: 'AUTH_INVALID_CREDENTIALS_ERROR',
		INVALID_SESSION_EXPIRED: 'INVALID_SESSION_EXPIRED',
	},
	403: {
		FORBIDDEN_ERROR: 'FORBIDDEN_ERROR',
		SAME_EMAIL_ERROR: 'SAME_EMAIL_ERROR',
		INSUFFICIENT_PERMISSION_ERROR: 'INSUFFICIENT_PERMISSION_ERROR',
		OLD_PASSWORD_NOT_MATCH_ERROR: 'OLD_PASSWORD_NOT_MATCH_ERROR',
	},
	404: {
		RESOURCE_NOT_FOUND_ERROR: 'RESOURCE_NOT_FOUND_ERROR',
	},
	500: {
		INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
	},
};

export default errorCatalog;
